/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IGU;

/**
 *
 * @author Chango
 */
public class InterfazGraficaAgenda extends javax.swing.JFrame {


   
//Declaro mi indice de forma global    
    int indice;
//Mis vectores para almacenar los datos de mis contactos declarado de forma global 
    String dniDatos [] = new String[10];
    String nombreDatos [] = new String[10];
    String apellidoDatos [] = new String[10];
    String direccionDatos [] = new String[10];
    String telefonoDatos [] = new String[10];
    String fechaNDatos [] = new String[10];
    
    
    public InterfazGraficaAgenda() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloEtiqueta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        dniEtiqueta = new javax.swing.JLabel();
        nombreEtiqueta = new javax.swing.JLabel();
        apellidoEtiqueta = new javax.swing.JLabel();
        direccionEtiqueta = new javax.swing.JLabel();
        telefonoEtiqueta = new javax.swing.JLabel();
        fnacEtiqueta = new javax.swing.JLabel();
        textDni = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textApellido = new javax.swing.JTextField();
        textDireccion = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        textFechaN = new javax.swing.JTextField();
        btnIzquierda = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        indiceEtiqueta = new javax.swing.JLabel();
        textIndice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloEtiqueta.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        tituloEtiqueta.setForeground(new java.awt.Color(5, 4, 84));
        tituloEtiqueta.setText("Agenda Electrónica");

        jSeparator2.setForeground(new java.awt.Color(135, 136, 140));

        dniEtiqueta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dniEtiqueta.setForeground(new java.awt.Color(49, 35, 130));
        dniEtiqueta.setText("DNI       :");

        nombreEtiqueta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombreEtiqueta.setForeground(new java.awt.Color(49, 35, 130));
        nombreEtiqueta.setText("Nombre :");

        apellidoEtiqueta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apellidoEtiqueta.setForeground(new java.awt.Color(49, 35, 130));
        apellidoEtiqueta.setText("Apellido :");

        direccionEtiqueta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        direccionEtiqueta.setForeground(new java.awt.Color(49, 35, 130));
        direccionEtiqueta.setText("Direccion  :");

        telefonoEtiqueta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        telefonoEtiqueta.setForeground(new java.awt.Color(49, 35, 130));
        telefonoEtiqueta.setText("Telefono  :");

        fnacEtiqueta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fnacEtiqueta.setForeground(new java.awt.Color(49, 35, 130));
        fnacEtiqueta.setText("F. Nac      :");

        btnIzquierda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIzquierda.setText("<<");
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });

        btnGrabar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnDerecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDerecha.setText(">>");
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });

        indiceEtiqueta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        indiceEtiqueta.setText("Indice:");

        textIndice.setEditable(false);
        textIndice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textIndice.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apellidoEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dniEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textDni, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(textNombre)
                    .addComponent(textApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(direccionEtiqueta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telefonoEtiqueta)
                    .addComponent(fnacEtiqueta))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(textTelefono)
                    .addComponent(textFechaN))
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(162, 162, 162)
                            .addComponent(tituloEtiqueta))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIzquierda)
                            .addComponent(indiceEtiqueta))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGrabar)
                                .addGap(30, 30, 30)
                                .addComponent(btnDerecha))
                            .addComponent(textIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tituloEtiqueta)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniEtiqueta)
                    .addComponent(direccionEtiqueta)
                    .addComponent(textDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreEtiqueta)
                    .addComponent(telefonoEtiqueta)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoEtiqueta)
                    .addComponent(fnacEtiqueta)
                    .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzquierda)
                    .addComponent(btnGrabar)
                    .addComponent(btnDerecha))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indiceEtiqueta))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
        
        //Guardo el numero que aparece en mi jTextFiel indice 
        indice = Integer.parseInt(textIndice.getText());//Lo convierto de String a int con Integer.parseInt()
        
        indice = indice -1;//al hacer clik en el boton de la izquierda el indice disminuye 

         if (indice >= 0) {//Si se cumple la condicion
                                     
            textIndice.setText(Integer.toString(indice));//Imprime el nuevo indice, pasando el valor de mi indice de int a string
            
            //Imprimo los datos en mis TextFiel segun el indice 
            textDni.setText(dniDatos[indice]);
            textNombre.setText(nombreDatos[indice]);
            textApellido.setText(apellidoDatos[indice]);
            textDireccion.setText(direccionDatos[indice]);
            textTelefono.setText(telefonoDatos[indice]);
            textFechaN.setText(fechaNDatos[indice]);
               
         }
         
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
         
         //Guardo el numero que aparece en mi jTextFiel indice
         indice = Integer.parseInt(textIndice.getText());//Lo convierto de String a int con Integer.parseInt()
         indice = indice + 1; // el indice aumenta en 1

        if (indice < 10) {
        
            textIndice.setText(Integer.toString(indice));//Imprime el nuevo indice, pasando el valor de mi indice de int a string 
            
            //Imprimo los datos en mis TextFiel segun el indice 
            textDni.setText(dniDatos[indice]);
            textNombre.setText(nombreDatos[indice]);
            textApellido.setText(apellidoDatos[indice]);
            textDireccion.setText(direccionDatos[indice]);
            textTelefono.setText(telefonoDatos[indice]);
            textFechaN.setText(fechaNDatos[indice]);
        
        }   

    }//GEN-LAST:event_btnDerechaActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
 
         //Guardo el numero que aparece en mi jTextFiel indice
          indice = Integer.parseInt(textIndice.getText());//Lo convierto de String a int con Integer.parseInt()
         
        //Capturo en varibles mis datos de los TextFiel 
         String dni = textDni.getText();
         String nombre = textNombre.getText();
         String apellido = textApellido.getText();
         String direccion = textDireccion.getText();
         String telefono = textTelefono.getText();
         String fechaN = textFechaN.getText();

         if (indice >= 0 && indice < 10) {//Si se cumple la condicion me permite guarda los datos 
                
               //guardo mis datos en los vectores segun el indice capturado en el TextFiel indice 
                dniDatos [indice] = dni;
                nombreDatos [indice] = nombre ;
                apellidoDatos [indice] = apellido ;
                direccionDatos [indice] = direccion;
                telefonoDatos [indice] = telefono;
                fechaNDatos [indice] = fechaN;
        }
              
    }//GEN-LAST:event_btnGrabarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoEtiqueta;
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JLabel direccionEtiqueta;
    private javax.swing.JLabel dniEtiqueta;
    private javax.swing.JLabel fnacEtiqueta;
    private javax.swing.JLabel indiceEtiqueta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nombreEtiqueta;
    private javax.swing.JLabel telefonoEtiqueta;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textDni;
    private javax.swing.JTextField textFechaN;
    private javax.swing.JTextField textIndice;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textTelefono;
    private javax.swing.JLabel tituloEtiqueta;
    // End of variables declaration//GEN-END:variables
}
